export const LOAD_INDEX_DATA = 'LOAD_INDEX_DATA';
export const LOAD_INDEX_DATA_SUCCESS = 'LOAD_INDEX_DATA_SUCCESS';
export const LOAD_INDEX_DATA_FAILURE = 'LOAD_INDEX_DATA_FAILURE';
export const SWITCH_INDEX_TYPE = 'SWITCH_INDEX_TYPE';
